### ISSUE TITLE
fence OSError

### ISSUE THREAD

**Issue by zhengyansheng** [uc-cdis/gen3-helm#204]
# pod fence OSError，How to solve it
│ fence Tue Oct 29 02:50:44 2024 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /_status (172.27.16.38)
│ fence OSError: write error
│ fence [2024-10-29 02:50:44,803][     fence][  ERROR] Can't get user info
│ fence Traceback (most recent call last):
│ fence   File "/fence/fence/resources/openid/orcid_oauth2.py", line 44, in get_auth_info
│ fence     claims = self.get_jwt_claims_identity(token_endpoint, jwks_endpoint, code)
│ fence   File "/fence/fence/resources/openid/idp_oauth2.py", line 79, in get_jwt_claims_identity
│ fence     token = self.get_token(token_endpoint, code)
│ fence   File "/fence/fence/resources/openid/idp_oauth2.py", line 56, in get_token
│ fence     return self.session.fetch_token(
│ fence   File "/usr/local/lib/python3.9/site-packages/authlib/oauth2/client.py", line 211, in fetch_token
│ fence     return self._fetch_token(
│ fence   File "/usr/local/lib/python3.9/site-packages/authlib/oauth2/client.py", line 368, in _fetch_token
│ fence     return self.parse_response_token(resp)
│ fence   File "/usr/local/lib/python3.9/site-packages/authlib/oauth2/client.py", line 344, in parse_response_token
│ fence     raise self.oauth_error_class(
│ fence authlib.integrations.base_client.errors.OAuthError: invalid_grant: Reused authorization code: B7FvgC
│ fence [2024-10-29 02:50:44,804][fence.error_handler][  ERROR] 400 HTTP error occured. ID: e87062e7-1673-4fd7-ab50-a31500c45a63
│ fence Details: {'message': 'OAuth2 callback error: no \'orcid\' in {\'error\': "Can\'t get your orcid: invalid_grant: Reused authorization code: B7FvgC"}'}

**Comment by michaelfitzo** [comment]
Closing.  I believe this was solved in our Gen3 community slack channel, but please reach out on slack if you still have questions.
