### ISSUE TITLE
BUG: Short description of the bug

### ISSUE THREAD

**Issue by zhengyansheng** [uc-cdis/gen3-helm#205]
# useryaml pod error

```bash
# kubectl -n gen3 logs useryaml-45hps
│ ERROR:gen3users:Permission 'reader' in role 'reader' in policy 'open_data_reader' has 'service = *'. This is unsecure because policy 'open_data_reader' is granted to publi
│ ERROR:gen3users:Permission 'storage_reader' in role 'storage_reader' in policy 'open_data_reader' has 'service = *'. This is unsecure because policy 'open_data_reader' is
│ ERROR:gen3users:Permission 'reader' in role 'reader' in policy 'full_open_access' has 'service = *'. This is unsecure because policy 'full_open_access' is granted to publi
│ ERROR:gen3users:Permission 'storage_reader' in role 'storage_reader' in policy 'full_open_access' has 'service = *'. This is unsecure because policy 'full_open_access' is
│ ERROR:gen3users:Permission 'reader' in role 'reader' in policy 'open_data_reader' has 'service = *'. This is unsecure because policy 'open_data_reader' is granted to publi
│ [2024-11-05 07:28:48,034][user_syncer][  ERROR] user.yaml validation failed. See errors in previous logs.
│ [2024-11-05 07:28:48,034][user_syncer][  ERROR] aborting early
│ ERROR:gen3users:Permission 'storage_reader' in role 'storage_reader' in policy 'open_data_reader' has 'service = *'. This is unsecure because policy 'open_data_reader' is
│ ERROR:gen3users:Permission 'reader' in role 'reader' in policy 'authn_open_access' has 'service = *'. This is unsecure because policy 'authn_open_access' is granted to pub
│ ERROR:gen3users:Permission 'storage_reader' in role 'storage_reader' in policy 'authn_open_access' has 'service = *'. This is unsecure because policy 'authn_open_access' i
│ Traceback (most recent call last):
│   File "/usr/local/bin/fence-create", line 6, in <module>
│     sys.exit(main())
│   File "/fence/bin/fence_create.py", line 505, in main
│     sync_users(
│   File "/fence/fence/scripting/fence_create.py", line 516, in sync_users
│     syncer.sync()
│   File "/fence/fence/sync/sync_users.py", line 1532, in sync
│     self._sync(s)
│   File "/fence/fence/sync/sync_users.py", line 1596, in _sync
│     user_yaml = UserYAML.from_file(
│   File "/fence/fence/sync/sync_users.py", line 174, in from_file
│     validate_user_yaml(file_contents)  # run user.yaml validation tests
│   File "/usr/local/lib/python3.9/site-packages/gen3users/validation.py", line 58, in validate_user_yaml
│     raise AssertionError(
│ AssertionError: user.yaml validation failed. See errors in previous logs.
│ Stream closed EOF for gen3/useryaml-45hps (fence)
```

`Please help me how to solve this error`

**Comment by EliseCastle23** [comment]
Hello! 

It seems the default useryaml was a bit outdated so it was failing the validation check. We just pushed up [this](https://github.com/uc-cdis/gen3-helm/commit/1a79dbe1f6cd34944ed46b58a14dab1d50b16941#diff-614d21f5fd311cb24061d8fd546d37cc05a2dcfdb0c6241dea7031459ccb151b) fix. Thank you for brining this issue to our attention- we really appreciate it!
